#  analysis_options.yaml
#  Ce fichier définit les règles de lint et d'analyse pour garantir un style de code cohérent.

include: package:lints/recommended.yaml

linter:
  rules:
    # Règles supplémentaires pour renforcer la qualité du code
    - prefer_const_constructors
    - avoid_print
    - prefer_final_fields
    - always_declare_return_types
    - annotate_overrides
    - avoid_unused_constructor_parameters
    - prefer_single_quotes
    - unnecessary_this
    - use_super_parameters

analyzer:
  errors:
    # Transforme certains avertissements en erreurs
    unused_import: error
    dead_code: error
    unused_local_variable: warning
