# analysis_options.yaml
# Règles strictes de linting pour garantir un code propre et cohérent

include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_const_constructors
    - avoid_print
    - prefer_final_fields
    - always_declare_return_types
    - annotate_overrides
    - avoid_unused_constructor_parameters
    - prefer_single_quotes
    - unnecessary_this
    - use_super_parameters
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - require_trailing_commas
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators

analyzer:
  errors:
    unused_import: error
    dead_code: error
    unused_local_variable: error
    missing_return: error
    invalid_override_of_non_virtual_member: error
